import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../../globals.css";
import {ProductContextProvider} from "@/contexts/ProductContext";
import {BrandContextProvider} from "@/contexts/BrandContext";
import {CategoryContextProvider} from "@/contexts/CategoryContext";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "QPick | Dashboard",
    description: "Generated by create next app",
};

export default function NoLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <body
            className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen flex flex-col`}
        >
            <div className="flex-1 flex">
                <BrandContextProvider>
                    <CategoryContextProvider>
                        <ProductContextProvider>
                            {children}
                        </ProductContextProvider>
                    </CategoryContextProvider>
                </BrandContextProvider>
            </div>
        </body>
        </html>
    );
}
